### ISSUE TITLE
Wrong behavior with multiple escaped characters

### ISSUE THREAD

**Issue by evilebottnawi** [mathiasbynens/cssesc#10]
Input:
```css
.class { content: "\F10C \F10D" }
```
Output:
```css
.class { content: "\F10C  \F10D" } /* Two space between escaped characters */
```
